pybo/views/answer_views.py
from datetime import datetime # 날짜와 시간을 동시에 표현하기 위한 모듈

from flask import Blueprint # bp 생성
from flask import url_for
from flask import request # db에 데이터 요청하기 위함
from flask import render_template
from flask import g # g.user는 세션에 저장된 사용자 정보 데이터
from flask import flash # 강제로 오류를 발생시키는 함수로, 로직에 오류가 있을 경우 사용한다.
from werkzeug.utils import redirect 

from pybo import db 
from ..forms import AnswerForm # forms.py파일에서 AnswerForm 클래스 import 
from pybo.models import Question, Answer # models.py 파일의 Question, Answer 클래스
from pybo.views.auth_views import login_required # @login_required 적용

bp = Blueprint('answer', __name__, url_prefix='/answer') # bp 생성, 별칭: answer


@bp.route('/create/<int:question_id>', methods=('POST', )) # 질문에 대한 답변 생성 (POST 요청만 있음)
# methods 속성은 question_detail.html에서 답변을 저장하는 form 엘리먼트의 메소드 post와 같은 값을 지정.
@login_required # 로그인이 필요한 기능
def create(question_id): # question_id 는 바로 윗줄에서 매핑 규칙으로 전달됨.
    form = AnswerForm() # question_detail.html에서 작성된 데이터
    question = Question.query.get_or_404(question_id) # db에서 question_id(정수형)를 id 값으로 갖고 있는 question 객체를 
    # 찾아서(id는 고윳값이므로 get 함수를 이용해 조회) question에 저장, 여기서 question_id를 Answer모델의 속성 중 하나와 헷갈리지 말자.
    if form.validate_on_submit(): # 폼으로 들어온 데이터가 폼 양식에 맞을 때,
        content = request.form['content'] # request: 템플릿에서 form 엘리먼트로 전달된 데이터들을 얻을 수 있음.
        # request.form['content']: POST 폼 방식으로 전송된 데이터 항목 중 name 속성이 content인 값을 찾아서 content 객체에 저장
        # request: 플라스크에서 생성과정 없이 사용할 수 있는 기본 객체 -> 브라우저의 요청부터 응답까지의 처리 구간에서 request 객체 사용 가능. request를 통해 브라우저에서 요청한 정보를 확인
        # 데이터는 html 파일의 form 태그에서 주소를 정해서 create함수로 보냄.
        answer = Answer(content=content, create_date=datetime.now(), user=g.user) # 폼에서 전송된 데이터로 answer객체 구성, g.user는 세션에 저장된 사용자 정보 데이터
        question.answer_set.append(answer) # 해당 질문에 달린 답변들에 answer 객체 추가
        db.session.commit() # db 저장
        return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=question_id), answer.id)) # 답변 생성 후 화면을 질문 상세 화면으로 이동 
        # question 별칭의 블루프린트의 detail 함수로, question_id는 detail함수의 인자
        # '{}#answer_{}'.format(anser.id) -> 함수 수행 후, 지정해놓은 앵커로 이동 -> 내가 쓴 답변을 보려고 스크롤을 굳이 안내려도 됨.
    return render_template('question/question_detail.html', question=question, form=form) # 폼으로 들어온 데이터가 양식에 맞지 않을 때, 다시 질문 상세 페이지로 이동
    # 질문 상세 페이지에 필요한 해당 question과 오류가 난 form(AnswerForm)전달 -> 에러 표시


@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST')) # 답변 수정 
@login_required # 로그인이 필요한 기능
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user: # 사용자가 답변 작성자가 아니라면
        flash("수정 권한이 없습니다.") # 권한 없음
        return redirect(url_for('question.detail', question_id=answer.question.id)) # 답변 상세 페이지로 리다이렉트
    if request.method == "POST": # 'POST' 요청
        form = AnswerForm() # 사용자로부터 입력받은 데이터를 폼에 저장
        if form.validate_on_submit(): # 입력된 데이터가 양식에 맞으면
            form.populate_obj(answer) # 폼에 있는 데이터를 answer 객체에 업데이트
            answer.modify_date = datetime.now() # 수정 일시 저장
            db.session.commit() # db 저장
            return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id)) # 답변 수정후 질문 상세 페이지로 리다이렉트
    else: # 'GET' 요청
        form = AnswerForm(obj=answer) # 답변 수정할 수 있도록 기존 내용 폼에 저장
    return render_template('answer/answer_form.html', form=form) # 답변 수정 폼으로 이동, 기존 내용도 전송


@bp.route('delete/<int:answer_id>') 
@login_required # 로그인이 필요한 기능
def delete(answer_id): # 답변 삭제 함수
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user: # 사용자가 답변 작성자가 아니라면
        flash("삭제 권한이 없습니다.") # 삭제 권한 없음
    else: # 사용자가 답변 작성자라면
        db.session.delete(answer) # 데이터베이스에서 답변 삭제
        db.session.commit() # db 저장
    return redirect(url_for('question.detail', question_id=question_id)) # 질문 상세 페이지로 리다이렉트


@bp.route('/vote/<int:answer_id>')
@login_required # 로그인이 필요한 기능
def vote(answer_id): # 답변 추천 함수
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user: # 사용자가 답변 작성자라면
        flash("본인이 작성한 글을 추천할 수 없습니다.") # 추천 권한 없음
    else: # 사용자가 답변 작성자가 아니라면
        _answer.voter.append(g.user) # 답변 추천인 중에 사용자 추가
        db.session.commit() # db 저장
    return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=_answer.question.id), _answer.id)) # 질문 상세 페이지로 리다이렉트

pybo/views/question_views.py
from datetime import datetime # 날짜와 시각 저장용

from flask import Blueprint # URL과 함수의 매핑을 관리하기 위해 사용하는 클래스
from flask import render_template # 데이터를 render_template 함수의 파라미터로 전달하면 템플릿에서 해당 데이터로 화면을 구성할 수 있음. 
# 템플릿 파일: 파이썬 문법을 사용할 수 있는 html파일 
from flask import request # 플라스크는 요청 데이터를 추출해서 request 전역객체에 저장한다. 이를 통해 데이터에 접근할 수 있다.
from flask import url_for
from flask import g # g 전역변수 사용
from flask import flash # 강제로 오류를 발생시키는 함수로, 로직에 오류가 있을 경우 사용한다.
from werkzeug.utils import redirect

from .. import db # __init__.py 파일의 db 객체 import
from pybo.models import Question # models.py파일에서 Question모델 import -> question_list에 질문 목록 저장
from pybo.models import Answer, User # 검색 함수를 처리할 떄 필요함
from pybo.forms import QuestionForm # forms.py에서 폼 import
from ..forms import AnswerForm # forms.py 파일에서 폼 import
from pybo.views.auth_views import login_required # @login_required 적용

bp = Blueprint('question', __name__, url_prefix='/question') 
# 첫 번째 인수 'question'은 블루프린트의 "별칭". -> 이후 url_for 함수에서 사용됨.
# 두 번째 인수 __name__에는 모듈명인 'question_views'가 인수로 __init__.py에 전달됨.
# 세 번쨰로 url_prefix는 라우팅 함수의 에너테이션 URL 앞에 기본으로 붙일 접두어 URL임. 


@bp.route('/list/') # 질문 목록
def _list():
    page = request.args.get('page', type=int, default=1) # 페이지
    # ex) http://localhost:5000/question/list/?page=5 과 같은 GET 방식으로 요청한 url에서 page값을 가져올 때 사용됨. 
    # type=int: 페이지 값이 정수형, default=1: url에 page값이 없으면 기본값 1이 설정됨.
    kw = request.args.get('kw', type=str, default='') # 화면에서 전달받은 검색어
    question_list = Question.query.order_by(Question.create_date.desc()) # query: 데이터베이스에게 특정 데이터를 달라는 클라의 요청
    # order_by: 조회 결과를 정렬하는 함수
    # Question 모델의 question 객체들을 작성일시 기준 역순으로 정렬 -> question_list 변수에 저장
    if kw: # 화면에서 전달받은 검색어가 있으면
        search = '%%{}%%'.format(kw) # 검색어를 포함하는 내용을 찾기위해 search에 저장
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username).join(User, Answer.user_id == User.id).subquery() # 서브쿼리 생성
        # 답변과 사용자 모델을 조인하여 생성, 검색 조건에 사용할 답변 내용 Answer.content와 답변 작성자 User.username이 쿼리 조회 항목으로 추가됨.
        # 그리고 이 서브쿼리와 기존 모델인 질문 모델을 연결할수 있는 질문 id에 해당하는 Answer.question_id도 조회 항목에 추가
        # -> 서브쿼리를 생성하면 Question 모델과 서브쿼리를 아우터조인할 수 있다.
        question_list = question_list.join(User).outerjoin(sub_query, sub_query.c.question_id == Question.id).filter(Question.subject.ilike(search) | Question.content.ilike(search) | User.username.ilike(search) | sub_query.c.content.ilike(search) | sub_query.c.username.ilike(search)).distinct() 
        # 질문 작성자를 검색하기 위해 User 모델 조인. User 모델은 Question 모델과 1:1 관계이므로 아우터 조인할 필요가 없음. 
        # (Answer모델에는 question_id가 각각 저장되는 만큼 한 질문에 여러 답변이 종속되기에 1:다수 관계라고 볼 수 있음.)
        # sub_query.c.question_id에 사용한 c는 서브쿼리의 조회 항목 -> sub_query.c.question_id는 서브쿼리의 조회 항목 중 question_id를 의미
        # sub_query.c.question_id와 Question.id를 연결해서 모델 연결
        # 이제 sub_query를 아우터조인했으므로 sub_query의 조회 항목을 filter 함수에 조건으로 추가할 수 있다.
        # 검색 조건은 각각 OR조건으로 조회하도록 filter 함수 내에서 | 기호를 사용했다.
    question_list = question_list.paginate(page, per_page=10)
    # 조회한 데이터 question_list에 paginate함수로 페이징 적용
    # 첫 번째 인수 page는 현재 조회할 페이지의 번호, 두 번째 인수 per_page로 전달된 10은 페이지마다 보여 줄 게시물이 10개임을 의미
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)
    # question_list.html에 question_list 데이터를 넘겨주고 그 데이터로 템플릿 화면을 구성하게 함.



@bp.route('/detail/<int:question_id>/') # ex)question/detail/3 -> question_id가 3인 페이지 요청
def detail(question_id): # 질문 상세 페이지를 요청했을 때 실행되는 함수, 매개변수에는 바로 윗줄에서 매핑 규칙에 사용한 <int:question_id>가 전달됨. int: 숫자값이 매핑됨을 의미
    form = AnswerForm() # 답변 form 객체를 읽을 수 있게 함.
    question = Question.query.get_or_404(question_id) # 파라미터로 받은 아이디로 Question 모델의 question 객체를 가져와서 question 변수에 저장.
    # get_or_404: 해당 데이터를 찾을 수 없는 경우에 404 페이지를 출력
    return render_template('question/question_detail.html', question=question, form=form) 
    # question_detail.html에 question 데이터를 넘겨주고 그 데이터로 템플릿 화면을 구성, 답변 form 객체를 전달하여 오류를 표시할 수 있도록 함.


@bp.route('/create/', methods=('GET', 'POST')) # 질문 생성
@login_required # 로그인이 필요한 함수, 다음 데코레이터는 반드시 해당 함수 "바로" 위에 위치 해야함.
def create():
    form = QuestionForm() # GET 요청일 경우 -> 항목이 비어있는 폼, POST 요청일 경우 -> 사용자가 입력한 데이터가 들어간 폼
    if request.method == 'POST' and form.validate_on_submit(): # POST 요청
        # request.method: create 함수로 요청된 전송 방식 post: 데이터를 서버에 전송
        # form.validate_on_submit 함수: 전송된 폼 데이터의 정합성을 점검(QuestionForm 클래스의 각 속성에 지정한 DataRequired() 같은 점검 항목에 이상이 없는지 확인)
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user) # 폼으로 전달된 데이터를 question객체에 저장
        # 폼으로부터 전달 받은 데이터는 form.subject.data 의 형식으로 받고 있음.
        db.session.add(question) # db에 question 객체 추가
        db.session.commit() # db 저장
        return redirect(url_for('main.index')) # 질문 저장 뒤, main 블루프린트의 index 함수로 이동 -> 질문 목록 페이지로 이동
    return render_template('question/question_form.html', form=form) # GET 요청 -> 질문 생성 폼 페이지로 이동 (form은 빈 form일 것.)
    # question_form.html 템플릿에 전달하는 QuestionForm의 객체(form)는 템플릿에서 라벨이나 입력폼 등을 만들때 필요하다.


@bp.route('/modify/<int:question_id>', methods=('GET', 'POST')) 
@login_required # 로그인이 필요한 기능
def modify(question_id): # 질문 수정 함수
    question = Question.query.get_or_404(question_id)
    if g.user != question.user: # 만약 사용자와 글 작성자가 다르다면
        flash('수정 권한이 없습니다.') # 수정 권한 없음 ->
        return redirect(url_for('question.detail', question_id=question_id)) # 질문 상세 페이지로 리다이렉트
    if request.method == 'POST': # 'POST' 요청
        form = QuestionForm() # form으로 사용자가 입력한 내용을 받아옴
        if form.validate_on_submit(): # 입력한 내용이 양식에 맞으면
            form.populate_obj(question) # 폼에 들어있는 데이터를 question 객체에 업데이트
            question.modify_date = datetime.now() # 수정일시 저장
            db.session.commit() # db 저장
            return redirect(url_for('question.detail', question_id=question_id)) # 수정 후, 질문 상세 페이지로 이동
    else: # 'GET' 요청 -> 질문 수정 버튼을 누른 경우
        form = QuestionForm(obj=question) # 기존의 질문 객체를 폼에 저장
    return render_template('question/question_form.html', form=form) # 질문 작성 페이지로 이동 (기존 질문 객체 전송)


@bp.route('/delete/<int:question_id>')
@login_required # 로그인이 필요한 기능
def delete(question_id): # 질문 삭제 함수
    question = Question.query.get_or_404(question_id)
    if g.user != question.user: # 사용자가 글 작성자가 아니라면
        flash("삭제 권한이 없습니다.")
        return redirect(url_for('question.detail', question_id=question_id)) # 질문 상세 페이지로 리다이렉트
    db.session.delete(question) # 사용자가 작성자라면 질문 삭제
    db.session.commit() # db 저장
    return redirect(url_for('question._list')) # 질문 목록 페이지로 리다이렉트


@bp.route('/vote/<int:question_id>/') 
@login_required # 로그인이 필요한 기능
def vote(question_id): # 질문 추천 함수
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user: # 사용자가 질문 작성자라면
        flash("본인이 작성한 글은 추천할 수 없습니다.") # 추천 불가
    else: # 사용자가 질문 작성자가 아니라면
        _question.voter.append(g.user) # 질문 추천인 중에 사용자 추가
        # Question 모델의 voter는 여러 사람을 추가할 수 있는 다대다 관계이므로 append()함수로 추천인을 추가해야 한다.
        # question_voter 테이블의 구조상 같은 사용자가 같은 질문을 여러 번 추천해도 추천 횟수는 증가하지 않는다. 
        # 동일한 사용자를 append 할때 오류가 날것 같지만 내부적으로 중복되지 않도록 잘 처리된다.
        db.session.commit() # db 저장
    return redirect(url_for('question.detail', question_id=question_id)) # 질문 상세 페이지로 리다이렉트

pybo/templates/question/question_detail.html
{% extends 'base.html' %} <!-- base.html을 상속 받음 -->
{% block content %}
<div class="container my-3">
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2> <!-- 질문 제목 -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|markdown }}</div> <!-- 질문 내용 -->
            <div class="d-flex justify-content-end">
                {% if question.modify_date %} <!-- 답변 수정 날짜가 있다면 표시-->
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.user.username }}</div> <!-- 질문 글쓴이 추가 -->
                    <div>{{ question.create_date|datetime }}</div> <!-- 질문 작성 일시 -->
                </div>
            </div>
            <div class="my-3"> <!-- 질문 수정 버튼 --> 
                <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}"
                    class="recommend btn btn-sm btn-outline-secondary">추천
                    <span class="badge rounded-pill bg-success">{{ question.voter|length }}</span>
                </a> <!-- 질문 수정 버튼 옆에 추천 버튼 추가, 추천인 수 표시 -->
                {% if g.user == question.user %} <!-- 사용자가 글 작성자라면 -->
                <a href="{{ url_for('question.modify', question_id=question.id) }}" 
                    class="btn btn-sm btn-outline-secondary">수정</a> <!-- 수정 버튼 생성 -->
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary" 
                    data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a> <!-- 질문 삭제 버튼 -->
                    <!-- <삭제> 버튼은 <수정> 버튼과는 달리 href 속성값을 "javascript:void(0)"로 설정했다. -->
                    <!-- href 속성값을 javascript:void(0)로 설정하면 해당 링크를 클릭해도 아무런 동작도 하지 않는다. -->
                    <!-- 그리고 삭제를 실행할 URL을 얻기 위해 data-uri 속성을 추가하고, <삭제> 버튼이 눌리는 이벤트를 확인할 수 있도록 class 속성에 "delete" 항목을 추가해 주었다. -->
                    <!-- href에 삭제 URL을 직접 사용하지 않고 이러한 방식을 사용하는 이유는 삭제 버튼을 클릭했을때 "정말로 삭제하시겠습니까?" 와 같은 확인창이 필요하기 때문이다. -->
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 목록 -->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5> <!-- 답변 갯수 -->
    {% for answer in question.answer_set %} <!-- question.answer_set에 있는 데이터를 하나씩 꺼내 answer 객체에 대입 -->
    <a id="answer_{{ answer.id }}"></a> <!-- 앵커 태그: URL 호출시 원하는 위치로 이동, 아이디 속성은 답변 아이디로 설정 -> 답변 작성 후 리다이렉트 했을 때 스크롤을 안내려도 됨.-->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|markdown }}</div> <!-- answer 객체의 내용들을 나열, 마크다운 적용 -->
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %} <!-- 답변 수정 날짜가 있다면 표시 -->
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div> <!-- 답변 글쓴이 추가 -->
                    <div>{{ answer.create_date|datetime }}</div> <!-- answer 객체의 질문 작성일시 나열 -->
                </div>
            </div>
            <div class="my-3"> <!-- 답변 수정 -->
                <a href="javascript:void(0)" data-uri="{{ url_for('answer.vote', answer_id=answer.id) }}"
                    class="recommend btn btn-sm btn-outline-secondary">추천
                    <span class="badge rounded-pill bg-success">{{ answer.voter|length }}</span>
                </a> <!-- 답변 수정 버튼 옆에 추천 버튼 추가, 추천인 수도 표시 -->
                {% if g.user == answer.user %} <!-- 사용자가 답변 작성자라면 -->
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                    class="btn btn-sm btn-outline-secondary">수정</a> <!-- 답변 수정 버튼 생성 --> 
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a> <!-- 답변 삭제 버튼 생성 -->
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3"> <!-- 답변 등록 폼 -->
        <!-- form 태그: 사용자로부터 데이터를 입력을 받을 수 있도록 함. action 속성: form 제출시 데이터를 어디로 보낼지 지정(url) -->
        <!-- method 속성: 데이터를 보낼 때 사용할 HTTP 메서드 지정 -->
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %} <!-- form에 에러갸 있다면 -->
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %} <!-- 그 에러들 중 각 항목들에 대해 -->
            <strong>{{ form[field].label }}</strong> <!-- 에러가 일어난 라벨 표시 -->
            <ul>
                {% for error in errors %} <!-- 일어난 에러들 중에 -->
                <li>{{ error }}</li> <!-- 에러 내용 표시 -->
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <!-- 답변 등록 칸 -->
        <div class="mb-3">
            <textarea {% if not g.user %}disabled{% endif %}
                name="content" id="content" class="form-control" rows="10"></textarea>  <!-- 사용자가 로그아웃 상태라면 답변 등록이 불가능하게 설정 -->
            <!-- textarea 태그: 여러 줄을 입력할 수 있는 텍스트 필드, name 속성: 텍스트 요소의 이름 명시, id 속성: 요소의 고유 식별자, rows 속성: 총 10줄-->
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary"> <!-- 답변 등록 버튼 -->
            <!-- input 태그: form 태그에서 제일 중요한 역할로 사용자로부터 정보를 입력 받음. -->
            <!-- type 속성: 입력 태그의 유형(submit: 서버로 제출/전송하는 버튼) value 속성: 입력 태그의 초깃값(사용자가 변경할 수 있음)-->
        </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript"> // <script>태그: 자바스크립트와 같은 클라이언트 사이드 스크립트(client-side scripts)를 정의할 때 사용
    const delete_elements = document.getElementsByClassName("delete"); // delete라는 클래스를 포함하는 버튼이나 링크를 누르면 
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if (confirm("정말로 삭제하시겠습니까?")) { // "정말로 삭제?"라는 질문을 하고 확인을 선택하면 
                location.href = this.dataset.uri; // 해당 컴포넌트의 data-uri 값으로 url을 호출하라는 의미
            }; // data-uri 속성에 해당하는 'question.delete' URL이 호출될 것
        }); // 확인 대신 취소를 선택하면 아무 일도 일어나지 않음.
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if (confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="my-3"> <!-- 질문 등록 폼, form 태그: 사용자로부터 데이터를 입력을 받을 수 있도록 함. post: 서버에 데이터를 보냄.-->
        {{ form.csrf_token }} <!-- form 엘리먼트를 통해 전송된 데이터가 실제 웹 사이트에서 만들어진 데이터인지 검증하는 데 필요한 CSRF 토큰 -->
        <!-- 오류표시 Start --> <!-- create함수에서 form.validate_on_submit() 코드가 실패하면 폼에는 오류 내용이 자동으로 등록됨 -->
        {% if form.errors %} <!-- 등록된 오류 표시 -->
        <div class="alert alert-danger" role="alert"> 
            {% for field, errors in form.errors.items() %} <!-- field: subject나 content와 같은 입력 폼의 필드 -->
            <strong>{{ form[field].label }}</strong> <!-- strong 태그: 해당 콘텐츠의 중요성이나 심각함, 긴급함 등을 강조, 오류가 있는 필드의 label을 굵은 글씨로 --> 
            <ul>
                {% for error in errors %} <!-- 생긴 오류들 각각 -->
                <li>{{ error }}</li> <!-- 오류 내용 -->
                {% endfor %}}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject">제목</label> <!-- label 태그: 폼의 양식에 이름을 붙이는 태그 -->
            <!-- for속성을 통해 다른 요소의 결합할 수 있음(for 속성값 == 결합하고자 하는 요소의 id 속성값) -->
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
            <!-- input 태그: form 태그에서 제일 중요한 역할로 사용자로부터 정보를 입력 받음. -->
            <!-- type="text: 한 줄의 입력 필드, name 속성: 텍스트 요소의 이름 명시, id 속성: 요소의 고유 식별자 -->
            <!-- value 속성 -> 이미 전송된 데이터가 다시 설정됨.(제목만 입력하고 등록해서 다시 입력해야할 때 제목 내용이 지워지지 않음.) -->
            <!-- [or '']은 "현재 템플릿이 GET 방식으로 요청되는 경우 기존 입력값이 없으므로 None으로 출력되는 것을 방지하기 위해서 사용 -->
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
            <!-- textarea 태그: 여러 줄의 텍스트를 입력할 수 있는 텍스트 입력 영역 -->
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button> <!-- button 태그: form요소에 입력된 내용을 서버로 전송할 때 사용 -->
        <!-- type 속성 -> submit: form 요소에 제출용으로 사용된다. -->
        <!-- 데이터를 어디로 보내야할 지는 굳이 명시하지 않아도 된다. 질문 목록 페이지에서 질문 등록하기 버튼을 누르면 GET 요청으로 이 페이지가 켜지고 --> 
        <!-- 이 페이지의 주소 자체가 question/create/이기 때문에 여기서 폼을 post로 보내면 자동으로 create함수에 post요청이 간다. -->
    </form>
</div>
{% endblock %}